final kRegisterUserTable = 
  'CREATE TABLE Register_user ('
  ' name VARCHAR(30) NOT NULL,'
  ' first_last_name VARCHAR(30) NOT NULL,'
  ' second_last_name VARCHAR(30) NOT NULL,'
  ' dob VARCHAR(10) NOT NULL,'
  ' gender VARCHAR(1) NOT NULL,'
  ' email VARCHAR(40) NOT NULL PRIMARY KEY,'
  ' password VARCHAR(40) NOT NULL)';

final kRegisterChildTable = 
  'CREATE TABLE Register_child ('
  ' email VARCHAR(40) NOT NULL,'
  ' name VARCHAR(30) NOT NULL,'
  ' first_last_name VARCHAR(30) NOT NULL,'
  ' second_last_name VARCHAR(30) NOT NULL,'
  ' dob VARCHAR(10) NOT NULL,'
  ' diagnosis VARCHAR(20) NOT NULL,'
  ' CONSTRAINT fk_email FOREIGN KEY (email) REFERENCES Register_user(email)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' PRIMARY KEY(email, name, first_last_name, second_last_name))';

final kRegisterIncidencesTable =  
  'CREATE TABLE Register_incidences ('
  ' id INT IDENTITY(1,1),'
  ' email VARCHAR(40) NOT NULL,'
  ' name VARCHAR(30) NOT NULL,'
  ' first_last_name VARCHAR(30) NOT NULL,'
  ' second_last_name VARCHAR(30) NOT NULL,'
  ' incidence_name VARCHAR(50) NOT NULL,'
  ' incidence_date VARCHAR(10) NOT NULL,'
  ' CONSTRAINT fk_email FOREIGN KEY (email) REFERENCES Register_user(email)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_name FOREIGN KEY (name) REFERENCES Register_child(name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_first_last_name FOREIGN KEY (first_last_name) REFERENCES Register_child(first_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_second_last_name FOREIGN KEY (second_last_name) REFERENCES Register_child(second_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' PRIMARY KEY(email, name, first_last_name, second_last_name, id))';

final kIncidencesTable = 
  'CREATE TABLE Incidences ('
  ' name VARCHAR(30) NOT NULL,'
  ' first_last_name VARCHAR(30) NOT NULL,'
  ' second_last_name VARCHAR(30) NOT NULL,'
  ' feeling_watched NULL,'
  ' communiaction_trouble NULL,'
  ' anxious NULL,'
  ' sad NULL,'
  ' anormal_physyc_signal NULL,'
  ' isolate NULL,'
  ' lack_attention NULL,'
  ' tantrums NULL,'
  ' aggressions NULL,'
  ' problematic_enviroment NULL,'
  ' CONSTRAINT fk_name FOREIGN KEY (name) REFERENCES Register_child(name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_first_last_name FOREIGN KEY (first_last_name) REFERENCES Register_child(first_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_second_last_name FOREIGN KEY (second_last_name) REFERENCES Register_child(second_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' PRIMARY KEY (name, first_last_name, second_last_name))';

final kTestsTable = 
  'CREATE TABLE Tests ('
  ' id INT IDENTITY(1,1),'
  ' email VARCHAR(40) NOT NULL,'
  ' name VARCHAR(30) NOT NULL,'
  ' first_last_name VARCHAR(30) NOT NULL,'
  ' second_last_name VARCHAR(30) NOT NULL,'
  ' test_name VARCHAR(50) NOT NULL,'
  ' make_date VARCHAR(10) NOT NULL,'
  ' result VARCHAR(150) NOT NULL,'
  ' CONSTRAINT fk_email FOREIGN KEY (email) REFERENCES Register_user(email)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_name FOREIGN KEY (name) REFERENCES Register_child(name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_first_last_name FOREIGN KEY (first_last_name) REFERENCES Register_child(first_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' CONSTRAINT fk_second_last_name FOREIGN KEY (second_last_name) REFERENCES Register_child(second_last_name)'
  ' ON DELETE CASCADE'
  ' ON UPDATE CASCADE,'
  ' PRIMARY KEY(id, email, name, first_last_name, second_last_name))';